---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint . -c molecule/default/yaml-lint.yml
  ansible-lint .
  flake8 .
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
    privileged: true
    pre_build_image: true
scenario:
  name: default
  test_sequence:
    - lint
